### ISSUE TITLE
Mismatch when combining sources. 

### ISSUE THREAD

**Issue by adriaque** [BioDataFuse/pyBiodatafuse#107]
I think I found an issue possibly caused by the `utils.combine_sources` function that is causing a mismatch for some of the annotators when combining them into a single table. The problem is that not all annotator data frames have the same length and when combining them I just found that I have a mismatch in the MINERVA and the WikiPathways annotators. Casually, those annotators for generating the input data are using this `code data_df = get_identifier_of_interest(bridgedb_df, "NCBI Gene")` instead of this `data_df = get_identifier_of_interest(bridgedb_df, "Ensembl")` that for example, OpenTargets annotator is using. As the source of the identifiers is different and the mapping is not perfect the length of the data frame changes depending on which source ID you are using and that causes a mismatch when merging the data frames.

@tabbassidaloii 
@YojanaGadiya

**Comment by YojanaGadiya** [comment]
Thank you @adriaque for rasing this. @tabbassidaloii is now taking care of this in a dedicated PR.

**Comment by tabbassidaloii** [comment]
I couldn't find a bug in the scripts 
@adriaque can you please share the screanshot of the table or the input so I can reproduce the error?

**Comment by YojanaGadiya** [comment]
Closing due to no response.

**Comment by tabbassidaloii** [comment]
> Closing due to no response.

This has been fixed in one of the PRs
