### ISSUE TITLE
Fix uniprot mapper

### ISSUE THREAD

**Issue by YojanaGadiya** [BioDataFuse/pyBiodatafuse#114]
**Describe the bug**
The current uniprot mapper in BridgeDB picks up both TrEMBL and SwissProt entries. 

**Expected behavior**
We need to stick to just Swiss-Prot ones.

**Comment by YojanaGadiya** [comment]
No longer using Uniprot as means for proteins, we moved towards Ensembl id.

**Comment by YojanaGadiya** [comment]
Maybe more relevant to open in BridgeDB gitub @tabbassidaloii 😅

**Comment by tabbassidaloii** [comment]
it's fixed fix there so no need :)
should only test when we merge that branch in BDF :)
