### ISSUE TITLE
required checks for Bgee

### ISSUE THREAD

**Issue by tabbassidaloii** [BioDataFuse/pyBiodatafuse#116]
- the query is very slow even with two genes as input, any solution for improving?
- add confidence_level_name
    -  'confidence_level_name': 'high confidence level'

**Comment by tabbassidaloii** [comment]
@dssib could you please check?

**Comment by dssib** [comment]
will check!

**Comment by tabbassidaloii** [comment]
Thank you! The confidence level is being added by this PR: https://github.com/BioDataFuse/pyBiodatafuse/pull/120
@dssib is there a possibility to improve the efficiency of the query? for 4 genes it takes almost half an hour to get the output

**Comment by dssib** [comment]
yes, I have an idea - I think launching separate queries per gene will lead in much better performance, I will implement this during the next days

**Comment by dssib** [comment]
please check https://github.com/BioDataFuse/pyBiodatafuse/pull/124
