### ISSUE TITLE
required checks for MINERVA

### ISSUE THREAD

**Issue by tabbassidaloii** [BioDataFuse/pyBiodatafuse#117]
@adriaque 
Except for the gene symbol, what other ID can be extracted from the map?

**Comment by adriaque** [comment]
In theory, you can extract a wide variety of IDs from a specific protein but they are contained inside the 'references' list inside the entity. In the entity type protein you have 'ID' (symbol) and references (with other IDs such as ENSEBML, Uniprot...).

<img width="297" alt="Screenshot 2024-03-20 at 12 05 35" src="https://github.com/BioDataFuse/pyBiodatafuse/assets/113828670/3521d0bc-fec6-4e94-9914-9ac0db0466c3">

**Comment by tabbassidaloii** [comment]
Can you modify the annotator in such a way that you extract the relevant data based on Ensembl or Entenz IDs. Currently, you use gene symbols.
