### ISSUE TITLE
DisGeNet annotator returns empty results

### ISSUE THREAD

**Issue by dssib** [BioDataFuse/pyBiodatafuse#22]
E.g. for 7157 (or ENSEMBL ENSG00000141510) exporting the TSV file only shows NaNs (on a local install of the app):

<img width="669" alt="Screenshot 2023-10-31 at 15 10 42" src="https://github.com/BioDataFuse/pyBiodatafuse/assets/112887133/bffd2053-95f0-45c2-8296-49c228d9e7ea">

**Comment by dssib** [comment]
Reproduced same issue on the online version: https://biodatafuse.streamlit.app/

**Comment by tabbassidaloii** [comment]
Thanks for spotting the bug @dssib.
Fixed [here](https://github.com/BioDataFuse/pyBiodatafuse/pull/49)
