### ISSUE TITLE
annotator for MolMeDB

### ISSUE THREAD

**Issue by DominikMartinat** [BioDataFuse/pyBiodatafuse#7]
Create anotator for https://molmedb.upol.cz/. It will be useful with metabolites as an input.

**Comment by YojanaGadiya** [comment]
Example file - https://github.com/BioDataFuse/pyBiodatafuse/blob/main/src/pyBiodatafuse/annotators/disgenet.py

Don't forget to run `tox` in command line to ensure the git workflow/tests work

Bonus is writing the test for the function. (Example here - https://github.com/BioDataFuse/pyBiodatafuse/blob/main/tests/test_version.py)
