### ISSUE TITLE
Mapping disease ontologies

### ISSUE THREAD

**Issue by tabbassidaloii** [BioDataFuse/pyBiodatafuse#72]

**Comment by tabbassidaloii** [comment]
disgenet has the xrefs, it can be extracted and used to map diseases?

**Comment by YojanaGadiya** [comment]
Right! I think we discussed that we use UMLS as the disease id. So I think you have taken case of merging those nodes to some extend.

**Comment by tabbassidaloii** [comment]
Added a note for myself :D 
Didn't notice it is assigned to you :D

**Comment by tabbassidaloii** [comment]
Fixed
