### ISSUE TITLE
Labels are not showing when importing graphml file in neo4j

### ISSUE THREAD

**Issue by adriaque** [BioDataFuse/pyBiodatafuse#75]
I just noticed what I believe is a potential issue when importing the graphml file into neo4j. I was having problems with the visualisation on neo4j bloom. When using the apoc function for importing graphml files you have the option 'readLabels' which takes the 'labels' property from your graph and uses it as labels. The issue is in the generated graph the 'labels' property corresponds to a piece of text describing the node, and 'node_type' is the actual label. I replaced 'node_type' with 'labels' and renamed the previous 'labels' property 'names' and now I can visualise the nodes in neo4j bloom. I hope I am being clear otherwise we can have a call or something to explain myself.

This is the documentation of the apoc import graphml function

![screenshot_2024-02-21_at_16 20 48_720](https://github.com/BioDataFuse/pyBiodatafuse/assets/113828670/a63ecc83-aa1c-4286-8fb1-42f114c449c9)

**Comment by tabbassidaloii** [comment]
@adriaque This is also fixed now?

**Comment by adriaque** [comment]
Yes!
